// <auto-generated />
using System;
using DealerDatabase.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DealerDatabase.Data.Migrations
{
    [DbContext(typeof(DealerDbContext))]
    partial class DealerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("DealerDatabase.Data.Entities.Dealer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompanyRegistrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompanyStatus")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FcaReferenceNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("FcaStatus")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IcoExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("IcoRegistrationNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("IncorporationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Postcode")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredAddress")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("SafExpiry")
                        .HasColumnType("TEXT");

                    b.Property<string>("SafStatus")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StockCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telephone")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingAddress")
                        .HasColumnType("TEXT");

                    b.Property<string>("TradingName")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("VatIsValid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VatNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CompanyRegistrationNumber")
                        .IsUnique();

                    b.ToTable("Dealers");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerSourceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContributedFieldsJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("[]");

                    b.Property<int>("DealerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DealerId");

                    b.HasIndex("SourceSystem", "SourceRecordId")
                        .IsUnique();

                    b.ToTable("SourceRecords");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.DealerSourceRecord", b =>
                {
                    b.HasOne("DealerDatabase.Data.Entities.Dealer", "Dealer")
                        .WithMany("SourceRecords")
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");
                });

            modelBuilder.Entity("DealerDatabase.Data.Entities.Dealer", b =>
                {
                    b.Navigation("SourceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
